BEGIN TRANSACTION;
CREATE TABLE MYMEMBER
        (ID TEXT PRIMARY KEY,
        NAME TEXT,
        PASSWORD TEXT,
        REMARK TEXT);
INSERT INTO "MYMEMBER" VALUES('ygs','유관순','1234','삼월하늘');
INSERT INTO "MYMEMBER" VALUES('lss','이순신','1234','한산섬');
INSERT INTO "MYMEMBER" VALUES('ysd','윤선도','1234','지국총');
CREATE TABLE T1
    (ID TEXT PRIMARY KEY,
    NAME TEXT,
    PASSWORD TEXT,
    REMARK TEXT);
COMMIT;
